import * as XLSX from 'xlsx';
import { XMLParser } from 'fast-xml-parser';
import { fetchJson, fetchBuffer } from '../lib/http.mjs';
import { parseCsv } from '../lib/csv.mjs';
import { htmlToText, norm, safeUrl, uniq, detectDates, detectRates, detectCurrencyAmounts, normalizeCompanyCategories, normalizeAidTypes } from '../lib/utils.mjs';
import { inferThemes } from '../lib/concepts.mjs';
async function tabularResourceRows(resourceId,maxRows=8000){const all=[];let page=1;while(all.length<maxRows){const u=`https://tabular-api.data.gouv.fr/api/resources/${encodeURIComponent(resourceId)}/data/?page=${page}&page_size=500`;const {json}=await fetchJson(u,{timeoutMs:30000,retries:2});const rows=json.data||json.results||[];all.push(...rows);if(!rows.length||rows.length<500)break;page++;if(page>40)break}return all.slice(0,maxRows)}
const aliases={title:['titre','title','nom','name','intitule','intitulé','libelle','libellé','aid_nom'],objective:['objectif','objet','description','presentation','présentation','resume','résumé'],beneficiaries:['beneficiaires','bénéficiaires','public','public cible','beneficiary','aid_benef'],expenses:['depenses eligibles','dépenses éligibles','operations eligibles','opérations éligibles','aid_operations_el'],conditions:['conditions','criteres','critères','eligibilite','éligibilité','aid_conditions'],amount:['montant','financement','taux','aid_montant'],aidType:['nature','type aide','type d aide','nature aide','instrument'],deadline:['date fin','date_fin','cloture','clôture','deadline','echeance','échéance','date limite'],url:['url','lien','link','source','page']};
function pick(row,names){const entries=Object.entries(row||{});for(const a of names){const hit=entries.find(([k])=>norm(k)===norm(a)||norm(k).includes(norm(a)));if(hit&&String(hit[1]??'').trim())return hit[1]}return null}
function rowToAid(row,source,idx){const title=htmlToText(pick(row,aliases.title)||'');if(!title)return null;const objective=htmlToText(pick(row,aliases.objective)||''),benef=htmlToText(pick(row,aliases.beneficiaries)||''),expenses=htmlToText(pick(row,aliases.expenses)||''),conditions=htmlToText(pick(row,aliases.conditions)||''),amount=htmlToText(pick(row,aliases.amount)||''),deadlineRaw=String(pick(row,aliases.deadline)||''),url=safeUrl(pick(row,aliases.url)||source.url,source.url)||source.url,aidTypeText=htmlToText(pick(row,aliases.aidType)||''),all=[title,objective,benef,expenses,conditions,amount,aidTypeText].join(' '),aidTypes=normalizeAidTypes(all);if(!aidTypes.length)return null;const cats=normalizeCompanyCategories(benef),dates=detectDates(deadlineRaw),d=dates.at(-1)||null,rates=detectRates(amount),amounts=detectCurrencyAmounts(amount);return{id:`${source.id}_dg_${idx}`,canonicalId:`${source.id}_dg_${idx}`,sourceId:source.id,title,kind:/appel|aap|ami/i.test(title)?'AAP / AMI':'AIDE',objective:objective||null,beneficiaries:benef||null,companyCategories:uniq(cats),themes:inferThemes(all),scope:source.scope==='France'?'NATIONAL':'REGIONAL',regions:source.scope==='France'?['Toutes les Régions']:[source.scope],aidTypes,aidRate:{min:rates.length?Math.min(...rates):null,max:rates.length?Math.max(...rates):null,raw:amount||null,byCompanySize:[]},aidAmount:{min:amounts.length?Math.min(...amounts):null,max:amounts.length?Math.max(...amounts):null,raw:amount||null,byCompanySize:[]},projectsExpected:[],eligibleExpenses:expenses||null,openingDate:null,closingDate:d,finalClosingDate:d,deadlines:d?[{date:d,type:'CLOTURE'}]:[],permanent:false,prerequisites:conditions||null,selectionCriteria:null,attentionPoints:[],cdcLinks:[],sourceLinks:[{label:'Donnée ouverte officielle',url}],regulationLinks:[],officialPage:url,funder:[source.name],verification:{status:'A_REVERIFIER',sourceTier:'C',lastChecked:new Date().toISOString(),fieldEvidence:[{field:'objective',sourceUrl:url,sourceTier:'C',locator:'jeu de données',evidenceText:objective.slice(0,650),checkedAt:new Date().toISOString()}]}}}
async function parseResource(r,maxRows){if(r.id){try{return await tabularResourceRows(r.id,maxRows)}catch{}}const {buffer}=await fetchBuffer(r.url,{timeoutMs:45000,retries:2}),fmt=String(r.format||r.mime||'').toLowerCase();if(fmt.includes('json')||r.url.endsWith('.json')){const j=JSON.parse(buffer.toString('utf8'));return Array.isArray(j)?j:(j.data||j.results||[])}if(fmt.includes('csv')||r.url.endsWith('.csv'))return parseCsv(buffer.toString('utf8'));if(fmt.includes('xls')||/\.(xlsx?|ods)$/.test(r.url)){const wb=XLSX.read(buffer);return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}if(fmt.includes('xml')||r.url.endsWith('.xml')){const j=new XMLParser({ignoreAttributes:false}).parse(buffer.toString('utf8'));const a=j?.root?.data?.item||j?.data?.item||j?.items?.item||[];return Array.isArray(a)?a:[a]}return[]}
function datasetRelevant(d,source){const s=norm(`${d.title||''} ${d.description||''}`);if(source.datasetInclude&&new RegExp(source.datasetInclude,'i').test(s))return true;if(/(beneficiaires?|attribuees?|attribuées?|commandes? publiques?|marches? publics?)/i.test(s))return false;return /(aides? et appels?|catalogue.{0,30}aides?|dispositifs?.{0,30}aides?|guide.{0,20}aides?|aides?.{0,30}entreprises?|appels? a projets?)/i.test(s)}
export async function collectDataGouv(source,{log=console.log,maxDatasets=30,maxRows=8000}={}){const aids=[];let rowsSeen=0,resCount=0;if(source.resourceId){try{const rows=await tabularResourceRows(source.resourceId,maxRows);for(const row of rows){const a=rowToAid(row,source,rowsSeen++);if(a)aids.push(a)}if(aids.length)return{aids,discovered:rowsSeen,message:`API tabulaire: ${rowsSeen} lignes, ${aids.length} fiches`}}catch(e){log(`[${source.id}] API tabulaire indisponible: ${e.message}`)}}const q=source.query||source.orgQuery||source.name,{json}=await fetchJson(`https://www.data.gouv.fr/api/1/datasets/?q=${encodeURIComponent(q)}&page_size=${maxDatasets}`,{timeoutMs:30000,retries:2}),ds=(json.data||[]).filter(d=>datasetRelevant(d,source));for(const d of ds){for(const r of(d.resources||[])){if(rowsSeen>=maxRows)break;if(!/(csv|json|xls|ods|xml|parquet)/i.test(`${r.format||''} ${r.url||''}`))continue;try{const rows=await parseResource(r,Math.max(0,maxRows-rowsSeen));resCount++;for(const row of rows.slice(0,Math.max(0,maxRows-rowsSeen))){const a=rowToAid(row,source,rowsSeen);rowsSeen++;if(a)aids.push(a)}}catch(e){log(`[${source.id}] ressource ignorée: ${e.message}`)}}}return{aids,discovered:rowsSeen,message:`${ds.length} datasets pertinents, ${resCount} ressources, ${aids.length} fiches`}}
