import * as cheerio from 'cheerio';
import pdf from 'pdf-parse';
import { cleanTitle, detectCurrencyAmounts, detectRates, normalizeAidTypes, normalizeCompanyCategories, safeUrl, uniq, norm } from './utils.mjs';
import { inferThemes } from './concepts.mjs';
import { extractCalendar } from './calendar.mjs';
import { regulatoryFallbacks } from './regulatory-fallbacks.mjs';

const HEADINGS={
 objective:['objectif','objectifs','finalité','finalite','présentation','presentation','description','contexte et objectifs','à quoi sert','ambition'],
 beneficiaries:['bénéficiaire','beneficiaire','bénéficiaires','beneficiaires','qui peut','pour qui','public cible','éligibles','eligibles','porteurs éligibles'],
 themes:['thématique','thematique','priorités','priorites','axes','domaines ciblés','domaines cibles','secteurs ciblés','filières'],
 projectsExpected:['projets attendus','projet attendu','opérations éligibles','operations eligibles','projets éligibles','projets eligibles','nature des projets','actions éligibles','travaux attendus','projets recherchés'],
 eligibleExpenses:['dépenses éligibles','depenses eligibles','dépenses','depenses','assiette','coûts éligibles','couts eligibles','coûts admissibles','coûts retenus','dépenses retenues'],
 excludedExpenses:['dépenses non éligibles','depenses non eligibles','coûts non éligibles','couts non eligibles','dépenses exclues','ne sont pas éligibles'],
 prerequisites:['critères d’éligibilité','criteres d eligibilite','conditions d’éligibilité','conditions d eligibilite','conditions','pré-requis','prérequis','prerequis','éligibilité','eligibilite','conditions requises'],
 selectionCriteria:['critères de sélection','criteres de selection','sélection','selection','critères d’évaluation','criteres d evaluation','évaluation','evaluation','instruction et sélection','notation','analyse des projets'],
 financial:['montant','taux','financement','modalités financières','modalites financieres','aide accordée','aide accordee','intensité d’aide','intensite d aide','assiette et taux','régime de financement'],
 calendar:['calendrier','date limite','dates limites','clôture','cloture','échéance','echeance','relève','releve','dépôt','depot','vague','dates de dépôt'],
 disbursementTerms:['versement','modalités de versement','modalites de versement','paiement de l’aide','paiement de l aide','acompte','solde','avance à notification','décaissement'],
 repaymentTerms:['remboursement','modalités de remboursement','modalites de remboursement','durée du prêt','duree du pret','différé','differe','amortissement','échéancier','echeancier'],
 stateAidRules:['aides d’état','aides d etat','régime d’aide','regime d aide','de minimis','cumul','cumuls','encadrement temporaire'],
 applicationProcess:['candidater','modalités de dépôt','modalites de depot','dossier de candidature','pièces à fournir','pieces a fournir','comment déposer'],
 contact:['contact','interlocuteur','renseignements','questions'],
 programme:['programme','dispositif','cadre','france 2030','fonds']
};
const hNorm=s=>cleanTitle(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function classifyHeading(h){const n=hNorm(h);for(const[k,ls]of Object.entries(HEADINGS))if(ls.some(x=>n.includes(hNorm(x))))return k;return null}
export function extractSections(html,baseUrl){const $=cheerio.load(html);$('script,style,noscript,nav,header,footer,form,svg').remove();const main=$('main').first().length?$('main').first():$('body');const sections={};let current='objective',buf=[];const flush=()=>{if(buf.length){const txt=cleanTitle(buf.join(' \n '));if(txt)sections[current]=(sections[current]?sections[current]+' \n ':'')+txt;buf=[]}};main.find('h1,h2,h3,h4,h5,p,li,td,th,dt,dd').each((_,el)=>{const tag=el.tagName?.toLowerCase(),txt=$(el).text().replace(/\s+/g,' ').trim();if(!txt)return;if(/^h[1-5]$/.test(tag)){flush();const c=classifyHeading(txt);if(c)current=c;else if(tag==='h1'&&!sections.title)sections.title=txt}else if(txt.length<9000)buf.push(txt)});flush();const links=[];main.find('a[href]').each((_,a)=>{const href=safeUrl($(a).attr('href'),baseUrl),label=cleanTitle($(a).text()||$(a).attr('title')||'');if(href)links.push({url:href,label})});return{sections,links,title:cleanTitle($('h1').first().text()||$('title').text()),text:cleanTitle(main.text())}}
function classifyDocs(links=[]){const rx=/(cahier|cdc|r[eè]glement|modalit|annexe|faq|appel[aà] projets?|aap|ami|dossier de candidature|grille|budget|notice|formulaire|convention)/i;return links.filter(x=>/\.(pdf|docx?|xlsx?|ods|odt|rtf|zip)(?:$|\?)/i.test(x.url)||rx.test(`${x.label} ${x.url}`)).map(x=>({...x,type:/\.pdf(?:$|\?)/i.test(x.url)?'PDF':/r[eè]glement|cahier|cdc/i.test(x.label)?'REGLEMENT':/faq/i.test(x.label)?'FAQ':/grille/i.test(x.label)?'GRILLE':'DOCUMENT'}))}
function sentences(text=''){return String(text).replace(/\s+/g,' ').split(/(?<=[.;:])\s+|\n+/).map(x=>x.trim()).filter(x=>x.length>4)}
function sizeFinancial(text=''){const out=[];for(const l of sentences(text)){const cats=['STARTUP','PME','ETI','GE'].filter(c=>new RegExp(c==='STARTUP'?'start[- ]?up':c==='GE'?'grande[s]? entreprise[s]?|\\bGE\\b':c==='PME'?'\\bPME\\b|petite[s]? et moyenne[s]? entreprise[s]?':`\\b${c}\\b`,'i').test(l));if(!cats.length)continue;const rates=detectRates(l),amounts=detectCurrencyAmounts(l);for(const c of cats)out.push({category:c,rateMin:rates.length?Math.min(...rates):null,rateMax:rates.length?Math.max(...rates):null,amountMin:amounts.length?Math.min(...amounts):null,amountMax:amounts.length?Math.max(...amounts):null,raw:l})}return out}
function financialSemantics(text=''){const ss=sentences(text),aidS=ss.filter(s=>/(montant de l['’ ]?aide|aide.{0,40}(?:plafond|maximum|minim|comprise|entre)|subvention.{0,40}(?:plafond|maximum|minim|comprise|entre)|avance remboursable|avance récupérable|pr[eê]t.{0,30}(?:plafond|montant|compris))/i.test(s)),projectS=ss.filter(s=>/(co[uû]t total|assiette|d[eé]penses?.{0,35}(?:minimum|minimales|maximales|comprises|entre)|projet.{0,35}(?:minimum|minimal|maximum|compris|entre))/i.test(s));const aidAmounts=aidS.flatMap(detectCurrencyAmounts),projectAmounts=projectS.flatMap(detectCurrencyAmounts),rates=ss.filter(s=>/(taux|intensit[eé]|prise en charge|jusqu['’ ]?à)/i.test(s)).flatMap(detectRates);return{aidAmounts,projectAmounts,rates,aidRaw:aidS.join(' '),projectRaw:projectS.join(' ')}}
function aidSplit(text=''){const n=String(text),sub=[...n.matchAll(/(\d{1,3}(?:[.,]\d+)?)\s*%[^.;]{0,45}subvention/gi)].map(m=>Number(m[1].replace(',','.'))),ar=[...n.matchAll(/(\d{1,3}(?:[.,]\d+)?)\s*%[^.;]{0,55}(?:avance remboursable|avance r[eé]cup[eé]rable)/gi)].map(m=>Number(m[1].replace(',','.')));if(!sub.length&&!ar.length)return null;return{subventionPercent:sub[0]??null,advancePercent:ar[0]??null,raw:sentences(n).filter(s=>/%/.test(s)&&/(subvention|avance)/i.test(s)).slice(0,3).join(' ')}}
function evidence(field,value,url,sourceTier,locator){if(!value||(Array.isArray(value)&&!value.length))return null;const s=Array.isArray(value)?value.join(' • '):String(value);return{field,sourceUrl:url,sourceTier,locator,evidenceText:s.slice(0,850),checkedAt:new Date().toISOString()}}
function evidenceList(sections,values,url,sourceTier){const loc=f=>sections[f]?`section:${f}`:`page-text-match:${f}`;return[
 evidence('objective',values.objective,url,sourceTier,loc('objective')),evidence('themes',values.themes,url,sourceTier,loc('themes')),evidence('beneficiaries',values.beneficiaries,url,sourceTier,loc('beneficiaries')),evidence('projectsExpected',values.projectsExpected,url,sourceTier,loc('projectsExpected')),evidence('eligibleExpenses',values.eligibleExpenses,url,sourceTier,loc('eligibleExpenses')),evidence('excludedExpenses',values.excludedExpenses,url,sourceTier,loc('excludedExpenses')),evidence('prerequisites',values.prerequisites,url,sourceTier,loc('prerequisites')),evidence('selectionCriteria',values.selectionCriteria,url,sourceTier,loc('selectionCriteria')),evidence('financialTerms',sections.financial,url,sourceTier,'section:financial'),evidence('calendar',sections.calendar,url,sourceTier,'section:calendar'),evidence('disbursementTerms',values.disbursementTerms,url,sourceTier,loc('disbursementTerms')),evidence('repaymentTerms',values.repaymentTerms,url,sourceTier,loc('repaymentTerms')),evidence('stateAidRules',values.stateAidRules,url,sourceTier,loc('stateAidRules'))].filter(Boolean)}
export function extractFromHtml(html,{url,sourceTier='B',scope='NATIONAL',region=null}={}){const{sections,links,title,text}=extractSections(html,url),fallback=regulatoryFallbacks(text),fin=sections.financial||text,semantic=financialSemantics(fin),rates=semantic.rates.length?semantic.rates:detectRates(fin),fallbackAmounts=detectCurrencyAmounts(fin),amounts=semantic.aidAmounts.length?semantic.aidAmounts:fallbackAmounts,cal=extractCalendar(sections.calendar||text),cats=normalizeCompanyCategories(sections.beneficiaries||text),aidTypes=normalizeAidTypes(fin+' '+text),docs=classifyDocs(links),themes=uniq([...inferThemes([title,sections.themes,text].join(' '))]),projects=sections.projectsExpected?[sections.projectsExpected]:[];const values={objective:sections.objective||null,themes,beneficiaries:sections.beneficiaries||null,projectsExpected:projects,eligibleExpenses:sections.eligibleExpenses||null,excludedExpenses:sections.excludedExpenses||null,prerequisites:sections.prerequisites||null,selectionCriteria:sections.selectionCriteria||fallback.selectionCriteria||null,disbursementTerms:sections.disbursementTerms||fallback.disbursementTerms||null,repaymentTerms:sections.repaymentTerms||fallback.repaymentTerms||null,stateAidRules:sections.stateAidRules||fallback.stateAidRules||null};const evidence=evidenceList(sections,values,url,sourceTier);return{title,...values,companyCategories:cats,scope,regions:region?[region]:scope==='NATIONAL'?['Toutes les Régions']:[],aidTypes,aidSplit:aidSplit(fin),aidRate:{min:rates.length?Math.min(...rates):null,max:rates.length?Math.max(...rates):null,raw:sections.financial||null,byCompanySize:sizeFinancial(fin).map(x=>({category:x.category,min:x.rateMin,max:x.rateMax,raw:x.raw})).filter(x=>x.min!=null||x.max!=null)},aidAmount:{min:amounts.length?Math.min(...amounts):null,max:amounts.length?Math.max(...amounts):null,raw:semantic.aidRaw||sections.financial||null,byCompanySize:sizeFinancial(fin)},minimumProjectCost:semantic.projectAmounts.length?Math.min(...semantic.projectAmounts):null,maximumProjectCost:semantic.projectAmounts.length>1?Math.max(...semantic.projectAmounts):null,openingDate:cal.openingDate,closingDate:cal.closingDate,finalClosingDate:cal.finalClosingDate,deadlines:cal.deadlines,permanent:cal.permanent,programme:sections.programme||null,applicationProcess:sections.applicationProcess||fallback.applicationProcess||null,contact:sections.contact||fallback.contact||null,attentionPoints:[],cdcLinks:docs,sourceLinks:[{label:'Page officielle',url}],regulationLinks:docs,officialPage:url,verification:{status:'A_REVERIFIER',sourceTier,fieldEvidence:evidence}}}
export async function extractFromPdf(buffer,{url,scope='NATIONAL',region=null}={}){const pages=[];let pageNo=0;const pagerender=async pageData=>{pageNo++;const tc=await pageData.getTextContent({normalizeWhitespace:true,disableCombineTextItems:false});let text='';let lastY=null;for(const item of tc.items||[]){const y=item.transform?.[5];if(lastY!=null&&y!=null&&Math.abs(y-lastY)>3)text+='\n';else if(text&&!text.endsWith('\n'))text+=' ';text+=item.str||'';lastY=y}pages.push({page:pageNo,text});return text};const out=await pdf(buffer,{pagerender}),raw=pages.length?pages.map(p=>`[PAGE ${p.page}]\n${p.text}`).join('\n'):String(out.text||''),lines=raw.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);let html='<html><body><h1>Document officiel</h1>';for(const line of lines.slice(0,30000)){if(/^\[PAGE \d+\]$/.test(line)){html+=`<h5>${escapeHtml(line)}</h5>`;continue}const c=classifyHeading(line);if(c&&line.length<190)html+=`<h2>${escapeHtml(line)}</h2>`;else html+=`<p>${escapeHtml(line)}</p>`}html+='</body></html>';const rec=extractFromHtml(html,{url,sourceTier:'A',scope,region});for(const ev of rec.verification.fieldEvidence){ev.sourceTier='A';const needle=norm(ev.evidenceText).slice(0,70);const p=pages.find(x=>needle&&norm(x.text).includes(needle));ev.locator=p?`PDF p.${p.page}`:'PDF'}return rec}
function escapeHtml(s=''){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
